### Spring Boot Configuration ###
spring:
  # Data Configuration for MongoDB
  # embedded configuration
  # https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-mongo-embedded
  data:
    mongodb:
      port: 0
      database: smartdatastore

  # Spring Session Configuration
  session:
    timeout: 1m

# Logging - alternative you can use logback with log rotation
logging.file: datastore-service.log
logging:
  file:
    max-size: 5MB
    max-history: 10
  level:
    root: WARN
    org.springframework: INFO
    me.wirries.smartdatastore: INFO

## Application Configuration
# You can override this parameter with the program arguments
app:
  version: @project.version@
  security:
    logSessions: true
